### PR TITLE
Set "XhciPortLimit" to "Enabled"

### PR DESCRIPTION
**Pull request by miharik5**
#15

### CODE REVIEW

**Comment by lzhoang2801** [comment]
XhciPortLimit will be used when the temporary USB mapping solution is implemented. Currently, it is not required for every case. Let the USB mapping guide clarify this further for now

**Comment by Sooly890** [comment]
This should not be done on Big Sur 11.4 or greater

**Comment by lzhoang2801** [comment]
> This should not be done on Big Sur 11.4 or greater

If you haven't updated the news, the issue with XhciPortLimit has been fixed for newer versions of macOS since this commit: https://github.com/acidanthera/OpenCorePkg/commit/fb43d90309f3f78d12be3d34e4575530ba0cb0f2

**Comment by Sooly890** [comment]
I respect that - but I do still find AMD machines on the AMD OS X Discord that do still get boot issues with XhciPortLimit enabled.

**Comment by lzhoang2801** [comment]
> I respect that - but I do still find AMD machines on the AMD OS X Discord that do still get boot issues with XhciPortLimit enabled.

Once again, I’d like to mention the XhciPortLimit patch for macOS 11.3+ by ExtremeXT and Visual. You can find more information in the Telegram group. And most AMD systems on each controller do not exceed 15 ports, so please double-check your report for more clarity

**Pull request closed without merging**
